name: Publish CLI to npm

on:
  push:
    branches: [main]
    paths:
      - 'packages/cli/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install workspace dependencies
        run: npm install

      - name: Publish CLI to npm
        run: npm publish --workspace=packages/cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}