name: Publish CLI to npm

on:
  push:
    branches: [main]
    paths:
      - 'packages/cli/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install workspace dependencies
        run: npm install

      - name: Bump CLI version
        run: npm version patch --workspace=packages/cli

      - name: Publish CLI to npm
        run: npm publish --workspace=packages/cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add packages/cli/package.json
          git commit -m "chore: bump CLI version [skip ci]" || exit 0
          git push origin HEAD:main